### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by PaulOctopusZLWB** [xiaoye97/PotionCraft_MoreInformation#2]
两个功能建议：
1. 给需求药剂体系做一个触发机制（类似文字透明或者点击后显示），或者直接做成功能开关可选关闭。毕竟一部分游戏乐趣来源于阅读刁民的需求。
2. 压缩一部分提示文字大小，目前版本文字有点过于小了（27寸屏幕有些阅读困难。注意到目前在提示文字和原文字中有一个空行。

一个语言建议：
1. 物品尚未拥有的英文版改个翻译“Items not owned, recommended"

**Comment by xiaoye97** [comment]
药剂提示加了开关。
文本大小也做了修复。
翻译已采纳。
