### ISSUE TITLE
研磨进度问题

### ISSUE THREAD

**Issue by ZIDOUZI** [xiaoye97/PotionCraft_MoreInformation#4]
研磨进度覆盖存档后不再显示，重新进入游戏后正常

**Comment by ZIDOUZI** [comment]
更正一下，是进度会显示在最顶部
![image](https://user-images.githubusercontent.com/53157536/210724085-567f5f75-64fe-478e-b8b6-c041d6719709.png)

**Comment by xiaoye97** [comment]
无法复现问题，你使用的是最新版本吗

**Comment by ZIDOUZI** [comment]
1.1.0版, 最新版未发现此问题
